---
- name: WiFi credentials
  ansible.builtin.template:
    src: NMConnection.j2
    dest: "/etc/NetworkManager/system-connections/{{ item.ssid }}.nmconnection"
    owner: root
    group: root
    mode: 0600
  with_items: "{{ wifi_creds }}"
  notify:
    - Restart network manager

- name: Disable NetworkManager MAC randomization
  ansible.builtin.copy:
    src: "disable_randmac.conf"
    dest: "/etc/NetworkManager/conf.d/disable_randmac.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart network manager

- name: Reload nm connection files
  shell: nmcli connection reload
